--1
SELECT * 
FROM ASIGNATURA a 
ORDER BY a.COSTEBASICO DESC, a.NOMBRE;   

--2
SELECT p2.NOMBRE ,p2.APELLIDO 
FROM PROFESOR p ,PERSONA p2 
WHERE p.DNI = p2.DNI ;

--3
SELECT a.NOMBRE 
FROM ASIGNATURA a , PROFESOR p , PERSONA p2 
WHERE a.IDPROFESOR= p.IDPROFESOR AND p.DNI = p2.DNI AND upper(p2.CIUDAD) LIKE 'SEVILLA'; 

--4
SELECT p.NOMBRE , p.APELLIDO 
FROM ALUMNO a ,PERSONA p 
WHERE a.DNI = p.DNI ;

--5
SELECT p.DNI , p.NOMBRE , p.APELLIDO 
FROM PERSONA p , ALUMNO a 
WHERE a.DNI = p.DNI AND upper(p.CIUDAD) LIKE 'SEVILLA'; 

--6
SELECT p.DNI , p.NOMBRE , p.APELLIDO 
FROM PERSONA p ,ALUMNO a ,ALUMNO_ASIGNATURA aa, ASIGNATURA a2  
WHERE aa.IDALUMNO = a.IDALUMNO 
AND a.DNI =p.DNI 
AND aa.IDASIGNATURA = a2.IDASIGNATURA 
AND upper(a2.NOMBRE)LIKE 'SEGURIDAD VIAL'; 

--7
SELECT DISTINCT a2.IDTITULACION  
FROM PERSONA p , ALUMNO a ,ALUMNO_ASIGNATURA aa ,ASIGNATURA a2
WHERE p.DNI = a.DNI AND a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND p.DNI LIKE '20202020A'; 

--8
SELECT a2.NOMBRE 
FROM PERSONA p , ALUMNO a , ALUMNO_ASIGNATURA aa , ASIGNATURA a2 
WHERE  p.DNI = a.DNI AND a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA =a2.IDASIGNATURA
AND upper(p.NOMBRE)LIKE 'ROSA' AND UPPER(p.APELLIDO)LIKE 'GARCIA';

--9
SELECT alumno.DNI 
FROM PERSONA alumno , ALUMNO a , ALUMNO_ASIGNATURA aa , ASIGNATURA a2 ,PROFESOR p2, PERSONA profesor
WHERE alumno.DNI = a.DNI AND a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.IDPROFESOR = p2.IDPROFESOR AND p2.DNI = profesor.DNI  
AND UPPER(profesor.NOMBRE) LIKE 'JORGE' AND UPPER(profesor.APELLIDO)LIKE 'SAENZ'; 

--10
SELECT alumno.DNI , alumno.NOMBRE , alumno.APELLIDO 
FROM PERSONA alumno, ALUMNO a , ALUMNO_ASIGNATURA aa , ASIGNATURA a2 , PROFESOR p , PERSONA profesor
WHERE alumno.DNI = a.DNI AND a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.IDPROFESOR = p.IDPROFESOR AND p.DNI = profesor.DNI
AND UPPER(profesor.NOMBRE) LIKE 'JORGE' AND UPPER(profesor.APELLIDO)LIKE 'SAENZ'; 

--11
SELECT  t.NOMBRE 
FROM TITULACION t ,ASIGNATURA a 
WHERE t.IDTITULACION = a.IDTITULACION 
AND a.CREDITOS =4;

--12
SELECT a.NOMBRE , a.CREDITOS , t.NOMBRE AS nombre_titulo
FROM TITULACION t , ASIGNATURA a 
WHERE t.IDTITULACION = a.IDTITULACION
AND a.CUATRIMESTRE =1;

--13
SELECT a2.NOMBRE , a2.COSTEBASICO, p.NOMBRE AS alumno
FROM PERSONA p , ALUMNO a , ALUMNO_ASIGNATURA aa , ASIGNATURA a2 
WHERE p.DNI = a.DNI 
AND a.IDALUMNO = aa.IDALUMNO 
AND aa.IDASIGNATURA = a2.IDASIGNATURA 
AND a2.CREDITOS >4.5;

--14
SELECT p.NOMBRE 
FROM PERSONA p , PROFESOR p2 , ASIGNATURA a 
WHERE p.DNI = p2.DNI 
AND p2.IDPROFESOR = a.IDPROFESOR 
AND a.COSTEBASICO BETWEEN 25 AND 35;

--15
SELECT p.NOMBRE
FROM PERSONA p ,ALUMNO a ,ALUMNO_ASIGNATURA aa 
WHERE p.DNI = a.DNI 
AND a.IDALUMNO = aa.IDALUMNO 
AND (aa.IDASIGNATURA ='150212'OR aa.IDASIGNATURA ='130113') OR (aa.IDASIGNATURA ='150212'AND aa.IDASIGNATURA ='130113');

--16
SELECT a.NOMBRE AS asignatura , t.NOMBRE AS titulacion
FROM ASIGNATURA a , TITULACION t 
WHERE t.IDTITULACION =a.IDTITULACION 
AND a.CREDITOS !=6 
AND a.CUATRIMESTRE =2;

--17
SELECT a2.NOMBRE , a2.CREDITOS *10 AS numero_horas, a.DNI 
FROM ALUMNO a , ALUMNO_ASIGNATURA aa ,ASIGNATURA a2 
WHERE a.IDALUMNO = aa.IDALUMNO 
AND aa.IDASIGNATURA = a2.IDASIGNATURA ;

--18
SELECT p.NOMBRE 
FROM PERSONA p , ALUMNO a ,ALUMNO_ASIGNATURA aa 
WHERE p.DNI =a.DNI 
AND a.IDALUMNO =aa.IDALUMNO 
AND p.VARON =0
AND p.CIUDAD like'Sevilla';

--19
SELECT a.NOMBRE 
FROM PROFESOR p , ASIGNATURA a 
WHERE p.IDPROFESOR = a.IDPROFESOR 
AND lower(p.IDPROFESOR) ='p101'
AND a.CURSO =1;

--20
SELECT p.NOMBRE 
FROM PERSONA p , ALUMNO a , ALUMNO_ASIGNATURA aa 
WHERE p.DNI = a.DNI 
AND a.IDALUMNO = aa.IDALUMNO 
AND aa.NUMEROMATRICULA >=3;








