alter session set "_oracle_script"=true;  
create user ejerUniversidad identified by ejerUniversidad;
GRANT CONNECT, RESOURCE, DBA TO ejerUniversidad;

--1
SELECT a.nombre,a.creditos FROM ASIGNATURA a ;
--2
SELECT distinct creditos FROM ASIGNATURA a ;
--3
SELECT * FROM PERSONA p ;
--4
SELECT a.NOMBRE ,a.CREDITOS FROM ASIGNATURA a WHERE a.CUATRIMESTRE =1;
--5
SELECT p.NOMBRE ,p.APELLIDO  FROM PERSONA p where to_char(FECHA_NACIMIENTO,'yyyy') <'1975';
--6
SELECT a.NOMBRE ,a.COSTEBASICO  FROM ASIGNATURA a WHERE creditos >4.5;
--7
SELECT a.NOMBRE  FROM ASIGNATURA a WHERE COSTEBASICO BETWEEN 25 AND 35;
--8
SELECT distinct  aa.IDALUMNO  FROM ALUMNO_ASIGNATURA aa  WHERE (aa.IDASIGNATURA ='150212'OR aa.IDASIGNATURA ='130113')OR (aa.IDASIGNATURA='150212'AND aa.IDASIGNATURA ='130113') ;
--9
SELECT a.NOMBRE  FROM ASIGNATURA a WHERE CUATRIMESTRE =2 AND NOT CREDITOS =6;
--10
SELECT p.NOMBRE ,p.APELLIDO  FROM PERSONA p WHERE APELLIDO LIKE 'G%';
--11
SELECT a.NOMBRE  FROM ASIGNATURA a WHERE IDTITULACION IS NULL ;
--12
SELECT a.NOMBRE  FROM ASIGNATURA a WHERE IDTITULACION IS NOT NULL ;
--13
SELECT a.NOMBRE  FROM ASIGNATURA a WHERE CREDITOS >8;
--14
SELECT a.NOMBRE ,a.CREDITOS *10 AS NumHoras FROM ASIGNATURA a ; 
--15
SELECT * FROM ASIGNATURA a WHERE CUATRIMESTRE =2 ORDER BY IDASIGNATURA ;
--16
SELECT p.NOMBRE  
FROM PERSONA p 
WHERE UPPER(CIUDAD) ='MADRID'AND VARON =0; 
--17
SELECT p.NOMBRE ,p.TELEFONO  
FROM PERSONA p 
WHERE p.TELEFONO LIKE '91%';
--18
SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE UPPER(a.NOMBRE) LIKE '%PRO%';
--19
SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.CURSO =1 AND a.IDPROFESOR ='P101';
--20
SELECT AA.IDALUMNO, AA.IDASIGNATURA 
FROM ALUMNO_ASIGNATURA aa 
WHERE AA.NUMEROMATRICULA >=3;
--21
SELECT A.NOMBRE,
A.COSTEBASICO,A.COSTEBASICO *1.10 AS PRECIO_PRIMERA_REPETICION,
a.COSTEBASICO *1.30 AS PRECIO_SEGUNDA_REPETICION,
a.COSTEBASICO *1.60 AS PRECIO_TERCERA_REPETICION
FROM ASIGNATURA a ;
--22
SELECT *
FROM PERSONA p 
WHERE TO_CHAR(P.FECHA_NACIMIENTO,'YYYY')<'1970';
--23 
--Sin join
SELECT DISTINCT P.IDPROFESOR 
FROM PROFESOR p ;
--Con join
SELECT DISTINCT P.IDPROFESOR 
FROM PROFESOR p ,PERSONA p2 
WHERE P.DNI=P2.DNI;

--24
SELECT aa.IDALUMNO 
FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA ='130122';
--25
SELECT DISTINCT aa.IDASIGNATURA 
FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDALUMNO IS NOT NULL ;
--26
SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.CREDITOS >4 AND (a.CUATRIMESTRE=1 OR a.CURSO=1);
--27
SELECT DISTINCT nvl(a.IDTITULACION, 'Sin codigo') 
FROM ASIGNATURA a ;

--28
SELECT p.DNI 
FROM PERSONA p 
WHERE upper(p.APELLIDO)LIKE'%G%';

--29
SELECT *
FROM PERSONA p 
WHERE P.VARON =1 
AND TO_CHAR(P.FECHA_NACIMIENTO,'YYYY')>'1970'
AND CIUDAD LIKE 'M%';





