--1
SELECT count(nvl(a.COSTEBASICO,0))AS nasignatura
FROM ASIGNATURA a ;

--2
SELECT COUNT(a.NOMBRE), t.NOMBRE  
FROM ASIGNATURA a ,TITULACION t 
WHERE a.IDTITULACION = t.IDTITULACION 
GROUP BY t.NOMBRE ;

--3
SELECT t.NOMBRE , SUM(a.COSTEBASICO)AS preciototal 
FROM TITULACION t , ASIGNATURA a 
WHERE t.IDTITULACION = a.IDTITULACION 
GROUP BY t.NOMBRE ;

--4
SELECT t.NOMBRE , SUM(a.COSTEBASICO) *1.07--Duda en donde aplicar el incremento
FROM TITULACION t, ASIGNATURA a 
WHERE upper(t.NOMBRE)LIKE 'MATEMATICAS' AND t.IDTITULACION = a.IDTITULACION 
GROUP BY t.nombre;

--5
SELECT COUNT(aa.IDALUMNO)AS totalAlumnos, a.IDASIGNATURA  
FROM ASIGNATURA a , ALUMNO_ASIGNATURA aa 
WHERE a.IDASIGNATURA = aa.IDASIGNATURA 
GROUP BY a.IDASIGNATURA ;

--6
SELECT a.NOMBRE , COUNT(aa.IDALUMNO)AS total_alumnos 
FROM ASIGNATURA a , ALUMNO_ASIGNATURA aa 
WHERE a.IDASIGNATURA = aa.IDASIGNATURA 
GROUP BY a.NOMBRE ;

--7 preguntar 
SELECT p.NOMBRE , SUM(a2.COSTEBASICO+aa.NUMEROMATRICULA)*1.10
FROM PERSONA p , ALUMNO a , ALUMNO_ASIGNATURA aa , ASIGNATURA a2 
WHERE p.DNI = a.DNI 
AND a.IDALUMNO = aa.IDALUMNO 
AND aa.IDASIGNATURA = a2.IDASIGNATURA 
GROUP BY p.NOMBRE ; 

--8
SELECT avg(a.COSTEBASICO) 
FROM ASIGNATURA a , TITULACION t , ALUMNO_ASIGNATURA aa 
WHERE a.IDASIGNATURA = aa.IDASIGNATURA 
AND a.IDTITULACION = t.IDTITULACION 
AND aa.NUMEROMATRICULA =1
GROUP BY t.NOMBRE  
HAVING sum(a.COSTEBASICO)>60 ;


--9
SELECT t.NOMBRE 
FROM TITULACION t , ASIGNATURA a , ALUMNO_ASIGNATURA aa 
WHERE t.IDTITULACION = a.IDTITULACION AND a.IDASIGNATURA = aa.IDASIGNATURA 
GROUP BY t.NOMBRE 
HAVING COUNT(aa.IDALUMNO)>3;


--10
SELECT p.CIUDAD , COUNT(p.DNI) 
FROM PERSONA p 
GROUP BY p.CIUDAD ;

--11
SELECT p2.NOMBRE , COUNT(a.IDASIGNATURA) 
FROM PROFESOR p , PERSONA p2 , ASIGNATURA a 
WHERE p2.DNI = p.DNI 
AND p.IDPROFESOR = a.IDPROFESOR 
GROUP BY p2.NOMBRE ;

--12
SELECT p.NOMBRE , COUNT(aa.IDALUMNO)AS total_alumno 
FROM PERSONA p , PROFESOR p2 , ASIGNATURA a , ALUMNO_ASIGNATURA aa 
WHERE p.DNI = p2.DNI 
AND p2.IDPROFESOR = a.IDPROFESOR 
AND a.IDASIGNATURA = aa.IDASIGNATURA 
GROUP BY p.NOMBRE 
HAVING COUNT(aa.IDALUMNO)>=2;

--13 
SELECT MAX(SUM(a.COSTEBASICO)) AS max_costes_cuatrimestres
FROM ASIGNATURA a 
GROUP BY a.CUATRIMESTRE ;

--14
SELECT sum(a.COSTEBASICO)AS coste_asignaturas
FROM ASIGNATURA a ;

--15
SELECT COUNT(a.IDASIGNATURA) AS n_asignaturas
FROM ASIGNATURA a ;

--16
SELECT MAX(a.COSTEBASICO) AS la_mas_cara, MIN(a.COSTEBASICO)AS la_mas_barata  
FROM ASIGNATURA a ;

--17
SELECT count(DISTINCT a.CREDITOS)AS n_posibilidades
FROM ASIGNATURA a ;

--18
SELECT count(DISTINCT a.CURSO)AS n_cursos
FROM ASIGNATURA a ;

--19
SELECT COUNT(DISTINCT p.CIUDAD) 
FROM PERSONA p ;

--20
SELECT a.NOMBRE ,a.CREDITOS *10
FROM ASIGNATURA a ;

--21
SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.IDTITULACION IS NULL ;

--22
SELECT p.NOMBRE ||' '||p.APELLIDO AS NombreCompleto, p.TELEFONO , p.DIRECCIONCALLE ||' '||p.DIRECCIONNUM AS Direccion
FROM PERSONA p ;

--23
SELECT EXTRACT(DAY FROM p.FECHA_NACIMIENTO)+1 AS siguiente_dia_de_nacimiento
FROM PERSONA p ;

--24
SELECT  EXTRACT(YEAR FROM sysdate)-EXTRACT (YEAR FROM p.fecha_nacimiento) AS años
FROM PERSONA p ;

--25
SELECT *
FROM PERSONA p 
WHERE EXTRACT(YEAR FROM sysdate)-EXTRACT (YEAR FROM p.fecha_nacimiento) >25;

--26
SELECT DISTINCT alu.NOMBRE ||' '|| alu.APELLIDO AS nombre_completo
FROM PERSONA alu, ALUMNO a , PERSONA prof, PROFESOR p 
WHERE alu.DNI = a.DNI 
AND prof.DNI = p.DNI 
AND p.DNI = a.DNI ;

--27
SELECT SUM(a.CREDITOS)AS suma_creditos 
FROM ASIGNATURA a , TITULACION t 
WHERE  t.IDTITULACION  = a.IDTITULACION
AND upper (t.NOMBRE) LIKE 'MATEMATICAS' ;

--28
SELECT COUNT(a.IDASIGNATURA) 
FROM ASIGNATURA a ,TITULACION t 
WHERE a.IDTITULACION = t.IDTITULACION 
AND upper (t.NOMBRE) LIKE 'MATEMATICAS' ;

--29
SELECT SUM(a.COSTEBASICO) 
FROM ALUMNO_ASIGNATURA aa ,ASIGNATURA a
WHERE aa.IDASIGNATURA = a.IDASIGNATURA 
GROUP BY aa.IDALUMNO ;

--30
SELECT COUNT(aa.IDASIGNATURA)  
FROM ALUMNO_ASIGNATURA aa 
GROUP BY aa.IDALUMNO ;




















