alter session set "_oracle_script"=true;  
create user residuos identified by residuos;
GRANT CONNECT, RESOURCE, DBA TO residuos;

--1
SELECT e.NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA e 
WHERE LOWER(e.CIUDAD_EMPRESA) like'huelva'
OR LOWER(e.CIUDAD_EMPRESA) like'malaga'
OR LOWER(e.CIUDAD_EMPRESA) like'málaga'
ORDER BY E.NOMBRE_EMPRESA DESC;

--2
SELECT d.NOMBRE_DESTINO 
FROM DESTINO d 
WHERE LOWER(d.CIUDAD_DESTINO)LIKE '%b%';

--3
SELECT rc.COD_RESIDUO 
FROM RESIDUO_CONSTITUYENTE rc 
WHERE rc.COD_CONSTITUYENTE =116
AND rc.CANTIDAD >4;

--4
SELECT t.TIPO_TRANSPORTE , t.KMS , t.COSTE 
FROM TRASLADO t 
WHERE EXTRACT(MONTH FROM t.FECHA_ENVIO)=12
AND EXTRACT (YEAR FROM t.FECHA_ENVIO)= 1994;

--5
SELECT rc.COD_RESIDUO , COUNT( rc.COD_CONSTITUYENTE)AS numeroConstituyente 
FROM RESIDUO_CONSTITUYENTE rc
GROUP BY rc.COD_RESIDUO ;

--6
SELECT nvl(avg(re.CANTIDAD),0) AS meidaResiduos
FROM RESIDUO_EMPRESA re
WHERE EXTRACT(YEAR FROM re.FECHA)=1994;

--7
SELECT MAX(t.KMS) 
FROM TRASLADO t 
WHERE EXTRACT (MONTH FROM t.FECHA_ENVIO)=3;

--8
SELECT t.NIF_EMPRESA, COUNT(DISTINCT rc.COD_CONSTITUYENTE) 
FROM TRASLADO t , RESIDUO r , RESIDUO_CONSTITUYENTE rc 
WHERE t.COD_RESIDUO = r.COD_RESIDUO 
AND r.COD_RESIDUO = rc.COD_RESIDUO 
GROUP BY t.NIF_EMPRESA 
HAVING COUNT( rc.COD_CONSTITUYENTE)>4;

--9
SELECT DISTINCT e.NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA e , TRASLADO t , RESIDUO r 
WHERE e.NIF_EMPRESA = t.NIF_EMPRESA 
AND t.COD_RESIDUO = r.COD_RESIDUO 
AND LOWER(r.OD_RESIDUO)LIKE '%metales%'; 

--10
SELECT e.CIUDAD_EMPRESA AS salida, d.CIUDAD_DESTINO AS destino, COUNT(t.COD_DESTINO) 
FROM EMPRESAPRODUCTORA e , TRASLADO t, DESTINO d 
WHERE e.NIF_EMPRESA = t.NIF_EMPRESA 
AND t.COD_DESTINO = d.COD_DESTINO 
GROUP BY e.CIUDAD_EMPRESA, d.CIUDAD_DESTINO

--11
SELECT  t.FECHA_ENVIO , e.NOMBRE_EMPTRANSPORTE
FROM EMPRESATRANSPORTISTA e ,EMPRESAPRODUCTORA e2 ,TRASLADO t ,RESIDUO r,RESIDUO_CONSTITUYENTE rc,CONSTITUYENTE c  
WHERE e.NIF_EMPTRANSPORTE = t.NIF_EMPTRANSPORTE 
AND t.NIF_EMPRESA =e2.NIF_EMPRESA
AND t.COD_RESIDUO = r.COD_RESIDUO 
AND r.COD_RESIDUO = rc.COD_RESIDUO 
AND rc.COD_CONSTITUYENTE  = c.COD_CONSTITUYENTE 
AND (LOWER( e2.CIUDAD_EMPRESA) like'malaga' OR LOWER(e2.CIUDAD_EMPRESA)like'huelva')
AND ( LOWER( c.NOMBRE_CONSTITUYENTE)like'bario' OR LOWER( c.NOMBRE_CONSTITUYENTE)like'lantano' )


--12
SELECT round (sum(t.COSTE /t.KMS ),2)AS total_por_kilometros
FROM TRASLADO t , EMPRESAPRODUCTORA e 
WHERE t.NIF_EMPRESA  = e.NIF_EMPRESA 
AND LOWER(e.NOMBRE_EMPRESA) LIKE 'carbonsur' ;

SELECT round(sum(t.COSTE) /sum(t.KMS),2) AS total_por_kilometros
FROM TRASLADO t , EMPRESAPRODUCTORA e 
WHERE t.NIF_EMPRESA  = e.NIF_EMPRESA 
AND LOWER(e.NOMBRE_EMPRESA) LIKE 'carbonsur' ;

--13
SELECT COUNT(rc.COD_CONSTITUYENTE) AS n_constituyentes
FROM RESIDUO_CONSTITUYENTE rc 
GROUP BY rc.COD_RESIDUO ;

--14
SELECT r.OD_RESIDUO , re.FECHA 
FROM RESIDUO r , RESIDUO_EMPRESA re , EMPRESAPRODUCTORA e 
WHERE  r.COD_RESIDUO = re.COD_RESIDUO 
AND re.NIF_EMPRESA = e.NIF_EMPRESA 
AND re.FECHA > SYSDATE -30
AND LOWER(e.NOMBRE_EMPRESA)like'%c%'
ORDER BY r.OD_RESIDUO , re.FECHA ;












