alter session set "_oracle_script"=true;  
create user jardineria identified by jardineria;
GRANT CONNECT, RESOURCE, DBA TO jardineria;

--1
SELECT c.NOMBRE_CLIENTE , e.NOMBRE ||' '||e.APELLIDO1 ||' '||e.APELLIDO2 AS representante_ventas
FROM CLIENTE c,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO ;

--2
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante
FROM CLIENTE c , EMPLEADO e ,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE ;

--3 
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante
FROM CLIENTE c , EMPLEADO e ,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--4
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante, o.CIUDAD 
FROM CLIENTE c , EMPLEADO e ,PAGO p , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA ;

--5
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante, o.CIUDAD 
FROM CLIENTE c , EMPLEADO e ,PAGO p , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA ;

--6
SELECT DISTINCT o.LINEA_DIRECCION1 , o.LINEA_DIRECCION2 
FROM OFICINA o , EMPLEADO e , CLIENTE c 
WHERE o.CODIGO_OFICINA = e.CODIGO_OFICINA 
AND e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS 
AND (LOWER( c.CIUDAD) LIKE 'fuenlabrada'
OR LOWER( c.REGION) LIKE 'fuenlabrada');

--7
SELECT DISTINCT  c.NOMBRE_CLIENTE , e.NOMBRE , o.CIUDAD 
FROM CLIENTE c ,EMPLEADO e , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA =o.CODIGO_OFICINA ;

--8
SELECT e.NOMBRE AS empleado, e2.NOMBRE AS jefe
FROM EMPLEADO e ,EMPLEADO e2 
WHERE e2.CODIGO_EMPLEADO = e.CODIGO_JEFE 

--9
SELECT DISTINCT  c.NOMBRE_CLIENTE 
FROM CLIENTE c ,PEDIDO p
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE 
AND p.FECHA_ESPERADA <p.FECHA_ENTREGA ;

--10
SELECT DISTINCT p.GAMA 
FROM GAMA_PRODUCTO gp , PRODUCTO p , DETALLE_PEDIDO dp ,PEDIDO p2 ,CLIENTE c 
WHERE gp.GAMA = p.GAMA 
AND p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO 
AND dp.CODIGO_PEDIDO = p2.CODIGO_PEDIDO 
AND p2.CODIGO_CLIENTE =c.CODIGO_CLIENTE ;

--Consultas multitabla (composición externa)
--1
SELECT c.*
FROM CLIENTE c ,PAGO p 
WHERE c.CODIGO_CLIENTE=p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--2
SELECT c.*
FROM CLIENTE c ,PEDIDO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--3
SELECT c.*
FROM CLIENTE c ,PAGO p ,PEDIDO p2 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND c.CODIGO_CLIENTE = p2.CODIGO_CLIENTE (+)
AND p2.CODIGO_CLIENTE IS NULL
AND p.CODIGO_CLIENTE IS NULL;

--4
SELECT e.*
FROM EMPLEADO e , OFICINA o  
WHERE e.CODIGO_OFICINA(+) = o.CODIGO_OFICINA 
AND e.CODIGO_OFICINA IS NULL;

--5
SELECT e.*
FROM CLIENTE c , EMPLEADO e
WHERE c.CODIGO_EMPLEADO_REP_VENTAS(+) = e.CODIGO_EMPLEADO
AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--6
SELECT e.*
FROM EMPLEADO e ,CLIENTE c 
WHERE e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS (+)
AND e.CODIGO_OFICINA IS NULL
AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--7
SELECT p.*
FROM PRODUCTO p , DETALLE_PEDIDO dp 
WHERE p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO (+)
AND dp.CODIGO_PRODUCTO IS NULL;

--8
SELECT o.CODIGO_OFICINA 
FROM OFICINA o , EMPLEADO e , CLIENTE c , PEDIDO p ,DETALLE_PEDIDO dp ,PRODUCTO p2 
WHERE o.CODIGO_OFICINA = e.CODIGO_OFICINA(+)
AND e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS
AND c.CODIGO_CLIENTE =p.CODIGO_CLIENTE 
AND p.CODIGO_PEDIDO = dp.CODIGO_PEDIDO 
AND dp.CODIGO_PRODUCTO = p2.CODIGO_PRODUCTO 
AND e.CODIGO_OFICINA IS NULL
AND LOWER( p2.GAMA) LIKE 'frutales';

SELECT o.CODIGO_OFICINA 
FROM OFICINA o 
WHERE o.CODIGO_OFICINA NOT IN
	(SELECT DISTINCT o.CODIGO_OFICINA 
	FROM PRODUCTO p , DETALLE_PEDIDO dp , PEDIDO p2 ,CLIENTE c ,EMPLEADO e 
	WHERE p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO 
	AND dp.CODIGO_PEDIDO = p2.CODIGO_PEDIDO 
	AND p2.CODIGO_CLIENTE = c.CODIGO_CLIENTE 
	AND c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
	AND LOWER( p.GAMA) LIKE 'frutales'
	);
	
--9
SELECT c.*
FROM CLIENTE c , PEDIDO p , PAGO p2 
WHERE c.CODIGO_CLIENTE = p.CODIGO_PEDIDO 
AND c.CODIGO_CLIENTE =p2.CODIGO_CLIENTE(+)
AND p2.CODIGO_CLIENTE IS NULL;

--10
SELECT DISTINCT  emp.*, jefe.NOMBRE 
FROM EMPLEADO emp, CLIENTE c , EMPLEADO jefe
WHERE emp.CODIGO_JEFE = jefe.CODIGO_EMPLEADO
AND emp.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS (+)

AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--Consultas resumen
--1
SELECT COUNT(e.CODIGO_EMPLEADO) 
FROM EMPLEADO e ;

--2
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c 
GROUP BY c.PAIS ;

--3
SELECT ROUND(AVG(p.TOTAL),1) 
FROM PAGO p 
WHERE EXTRACT (YEAR FROM p.FECHA_PAGO)=2009; 

--4
SELECT COUNT(p.CODIGO_PEDIDO) 
FROM PEDIDO p 
GROUP BY p.ESTADO 
ORDER BY COUNT(p.CODIGO_PEDIDO) DESC ;

--5
SELECT MAX(p.PRECIO_VENTA), MIN(p.PRECIO_VENTA)  
FROM PRODUCTO p ;

--6
SELECT COUNT(c.CODIGO_CLIENTE) AS n_clientes
FROM CLIENTE c ;

--7
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c , EMPLEADO e ,OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA 
AND LOWER(o.CIUDAD)like'madird'; 

--8
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c 
WHERE LOWER(c.CIUDAD) LIKE 'm%' 
GROUP BY c.CIUDAD ;

--9
SELECT e.CODIGO_EMPLEADO , COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c ,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
GROUP BY e.CODIGO_EMPLEADO ;

--10
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c ,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--11
SELECT MAX(p.FECHA_PAGO),MIN(p.FECHA_PAGO)  
FROM CLIENTE c ,PAGO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE 
GROUP BY c.CODIGO_CLIENTE ;

--12
SELECT COUNT(DISTINCT dp.CODIGO_PRODUCTO) 
FROM PEDIDO p ,DETALLE_PEDIDO dp , PRODUCTO p2 
WHERE p.CODIGO_PEDIDO = dp.CODIGO_PEDIDO 
GROUP BY p.CODIGO_PEDIDO ;

--13
SELECT SUM(dp.CANTIDAD) 
FROM DETALLE_PEDIDO dp 
GROUP BY dp.CODIGO_PEDIDO ;

--14 mal
SELECT * from(
SELECT dp.CODIGO_PRODUCTO ,COUNT(dp.CODIGO_PRODUCTO) 
FROM DETALLE_PEDIDO dp 
GROUP BY dp.CODIGO_PRODUCTO 
ORDER BY COUNT(dp.CODIGO_PRODUCTO) DESC)
WHERE rownum <=20;
--15
SELECT sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) AS base_imponible, 
sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) *0.21 AS iva ,
(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) +(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) *0.21 AS total
FROM PAGO p ,CLIENTE c ,PEDIDO p2 ,DETALLE_PEDIDO dp
WHERE p.CODIGO_CLIENTE = c.CODIGO_CLIENTE 
AND c.CODIGO_CLIENTE = p2.CODIGO_CLIENTE 
AND p2.CODIGO_PEDIDO = dp.CODIGO_PEDIDO 
;
--16
SELECT sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) AS base_imponible, sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) *0.21 AS iva ,(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) +(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) *0.21 AS total
FROM PAGO p ,CLIENTE c ,PEDIDO p2 ,DETALLE_PEDIDO dp
GROUP BY dp.CODIGO_PRODUCTO ;

--17
SELECT sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) AS base_imponible, sum(dp.PRECIO_UNIDAD*dp.CANTIDAD) *0.21 AS iva ,(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) +(sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)) *0.21 AS total
FROM PAGO p ,CLIENTE c ,PEDIDO p2 ,DETALLE_PEDIDO dp
WHERE dp.CODIGO_PRODUCTO LIKE 'OR%'
GROUP BY dp.CODIGO_PRODUCTO ;

--18
SELECT p.NOMBRE , sum(dp.CANTIDAD), sum(dp.PRECIO_UNIDAD*dp.CANTIDAD), sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)*1.21
FROM DETALLE_PEDIDO dp , PRODUCTO p 
WHERE dp.CODIGO_PRODUCTO =p.CODIGO_PRODUCTO 
GROUP BY p.NOMBRE 
HAVING sum(dp.PRECIO_UNIDAD*dp.CANTIDAD)>3000;

--Subconsultas
--1
SELECT c2.NOMBRE_CLIENTE 
FROM CLIENTE c2 
WHERE c2.LIMITE_CREDITO =
	(SELECT MAX(c.LIMITE_CREDITO) 
		FROM CLIENTE c );

	

--2
SELECT e.NOMBRE 
FROM EMPLEADO e , CLIENTE c 
WHERE e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS (+)
AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;
/*
SELECT e.NOMBRE 
FROM EMPLEADO e 
WHERE e.CODIGO_EMPLEADO in
	(SELECT c.CODIGO_EMPLEADO_REP_VENTAS  
	FROM CLIENTE c 
	WHERE c.CODIGO_CLIENTE(+)  IS NULL);

*/

--3
SELECT p2.NOMBRE 
FROM PRODUCTO p2 
GROUP BY p2.NOMBRE 
HAVING max(p2.PRECIO_VENTA)=
	(SELECT max(p.PRECIO_VENTA)
	FROM PRODUCTO p );

--4
SELECT p.NOMBRE 
FROM PRODUCTO p ,DETALLE_PEDIDO dp 
WHERE p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO 
GROUP BY p.CODIGO_PRODUCTO , p.NOMBRE 
HAVING sum(dp.CANTIDAD)=
	(SELECT max(sum(dp.CANTIDAD)
	FROM DETALLE_PEDIDO dp 
	GROUP BY dp.CODIGO_PEDIDO );
	
--5
SELECT c.*
FROM CLIENTE c
WHERE c.LIMITE_CREDITO > 
	(SELECT SUM(p.TOTAL) 
	FROM PAGO p 
	WHERE p.CODIGO_CLIENTE =c.CODIGO_CLIENTE 
	GROUP BY p.CODIGO_CLIENTE 
	);

--6
SELECT p.NOMBRE 
FROM PRODUCTO p 
WHERE p.CANTIDAD_EN_STOCK =(SELECT MAX(p2.CANTIDAD_EN_STOCK) FROM PRODUCTO p2)
OR p.CANTIDAD_EN_STOCK = (SELECT MIN(CANTIDAD_EN_STOCK)FROM PRODUCTO p3);
;
	
--7
SELECT e.NOMBRE , e.APELLIDO1 , e.EMAIL 
FROM EMPLEADO e 
WHERE e.CODIGO_JEFE =
	(SELECT e2.CODIGO_EMPLEADO  
	FROM EMPLEADO e2 
	WHERE LOWER(e2.NOMBRE)like'alberto' 
	AND LOWER(e2.APELLIDO1)LIKE 'soria' 
	);

--Consultas variadas
--1
SELECT c.NOMBRE_CLIENTE , COUNT(p.CODIGO_PEDIDO) 
FROM CLIENTE c , PEDIDO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
GROUP BY c.NOMBRE_CLIENTE ;

--2
SELECT c.NOMBRE_CLIENTE , sum(p.TOTAL)
FROM CLIENTE c , PAGO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
GROUP BY c.NOMBRE_CLIENTE ;

--3
SELECT c.NOMBRE_CLIENTE 
FROM CLIENTE c , PEDIDO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_PEDIDO 
AND EXTRACT(YEAR FROM p.FECHA_PEDIDO)= 2008
ORDER BY c.NOMBRE_CLIENTE;

--4
SELECT c.NOMBRE_CLIENTE , e.NOMBRE , e.APELLIDO1 , o.TELEFONO 
FROM CLIENTE c , EMPLEADO e ,OFICINA o , PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS null;

--5
SELECT c.NOMBRE_CLIENTE ,e.NOMBRE , e.APELLIDO1 , o.CIUDAD 
FROM CLIENTE c , EMPLEADO e , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA ;

--6
SELECT e.NOMBRE ,e.APELLIDO1 ,e.PUESTO ,o.TELEFONO 
FROM EMPLEADO e , CLIENTE c ,OFICINA o 
WHERE e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS(+) 
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA 
AND c.CODIGO_EMPLEADO_REP_VENTAS  IS NULL;

--7

SELECT o.CIUDAD , COUNT(e.CODIGO_EMPLEADO) 
FROM OFICINA o , EMPLEADO e 
WHERE o.CODIGO_OFICINA = e.CODIGO_OFICINA 
GROUP BY o.CIUDAD ;




