alter session set "_oracle_script"=true;  
create user jardineria identified by jardineria;
GRANT CONNECT, RESOURCE, DBA TO jardineria;

--1
SELECT c.NOMBRE_CLIENTE , e.NOMBRE ||' '||e.APELLIDO1 ||' '||e.APELLIDO2 AS representante_ventas
FROM CLIENTE c,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO ;

--2
SELECT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante
FROM CLIENTE c , EMPLEADO e ,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE ;

--3 mal
SELECT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante
FROM CLIENTE c , EMPLEADO e ,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--4
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante, o.CIUDAD 
FROM CLIENTE c , EMPLEADO e ,PAGO p , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA ;

--5
SELECT DISTINCT c.NOMBRE_CLIENTE AS cliente, e.NOMBRE AS representante, o.CIUDAD 
FROM CLIENTE c , EMPLEADO e ,PAGO p , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND c.CODIGO_CLIENTE = p.CODIGO_CLIENTE
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA ;

--6
SELECT DISTINCT o.LINEA_DIRECCION1 , o.LINEA_DIRECCION2 
FROM OFICINA o , EMPLEADO e , CLIENTE c 
WHERE o.CODIGO_OFICINA = e.CODIGO_OFICINA 
AND e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS 
AND LOWER( c.CIUDAD) LIKE 'fuenlabrada'
OR LOWER( c.REGION) LIKE 'fuenlabrada';

--7
SELECT c.NOMBRE_CLIENTE , e.NOMBRE , o.CIUDAD 
FROM CLIENTE c ,EMPLEADO e , OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA =o.CODIGO_OFICINA ;

--8
SELECT e.NOMBRE AS empleado, e2.NOMBRE AS jefe
FROM EMPLEADO e ,EMPLEADO e2 
WHERE e2.CODIGO_EMPLEADO = e.CODIGO_JEFE 

--9
SELECT DISTINCT  c.NOMBRE_CLIENTE 
FROM CLIENTE c ,PEDIDO p
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE 
AND p.FECHA_ESPERADA <p.FECHA_ENTREGA ;

--10
SELECT DISTINCT c.CODIGO_CLIENTE ,gp.*
FROM GAMA_PRODUCTO gp , PRODUCTO p , DETALLE_PEDIDO dp ,PEDIDO p2 ,CLIENTE c 
WHERE gp.GAMA = p.GAMA 
AND p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO 
AND dp.CODIGO_PEDIDO = p2.CODIGO_PEDIDO 
AND p2.CODIGO_CLIENTE =c.CODIGO_CLIENTE ;

--Consultas multitabla (composición externa)
--1
SELECT c.*
FROM CLIENTE c ,PAGO p 
WHERE c.CODIGO_CLIENTE=p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--2
SELECT c.*
FROM CLIENTE c ,PEDIDO p 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND p.CODIGO_CLIENTE IS NULL;

--3
SELECT c.*
FROM CLIENTE c ,PAGO p ,PEDIDO p2 
WHERE c.CODIGO_CLIENTE = p.CODIGO_CLIENTE (+)
AND c.CODIGO_CLIENTE = p2.CODIGO_CLIENTE (+)
AND p2.CODIGO_CLIENTE IS NULL;

--4
SELECT e.*
FROM EMPLEADO e , OFICINA o  
WHERE e.CODIGO_OFICINA(+) = o.CODIGO_OFICINA 
AND e.CODIGO_OFICINA IS NULL;

--5
SELECT e.*
FROM CLIENTE c , EMPLEADO e
WHERE c.CODIGO_EMPLEADO_REP_VENTAS(+) = e.CODIGO_EMPLEADO
AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--6
SELECT e.*
FROM EMPLEADO e ,CLIENTE c 
WHERE e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS (+)
AND e.CODIGO_OFICINA IS NULL
AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--7
SELECT p.*
FROM PRODUCTO p , DETALLE_PEDIDO dp 
WHERE p.CODIGO_PRODUCTO = dp.CODIGO_PRODUCTO (+)
AND dp.CODIGO_PRODUCTO IS NULL;

--8
SELECT o.*
FROM OFICINA o , EMPLEADO e , CLIENTE c , PEDIDO p ,DETALLE_PEDIDO dp ,PRODUCTO p2 
WHERE o.CODIGO_OFICINA = e.CODIGO_OFICINA(+)
AND e.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS
AND c.CODIGO_CLIENTE =p.CODIGO_CLIENTE 
AND p.CODIGO_PEDIDO = dp.CODIGO_PEDIDO 
AND dp.CODIGO_PRODUCTO = p2.CODIGO_PRODUCTO 
AND e.CODIGO_OFICINA IS NULL
AND LOWER( p2.GAMA) LIKE 'frutales'; 

--9
SELECT c.*
FROM CLIENTE c , PEDIDO p , PAGO p2 
WHERE c.CODIGO_CLIENTE = p.CODIGO_PEDIDO 
AND c.CODIGO_CLIENTE =p2.CODIGO_CLIENTE(+)
AND p2.CODIGO_CLIENTE IS NULL;

--10
SELECT DISTINCT  emp.*, jefe.NOMBRE 
FROM EMPLEADO emp, CLIENTE c , EMPLEADO jefe
WHERE emp.CODIGO_JEFE = jefe.CODIGO_EMPLEADO
AND emp.CODIGO_EMPLEADO = c.CODIGO_EMPLEADO_REP_VENTAS (+)

AND c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--Consultas resumen
--1
SELECT COUNT(e.CODIGO_EMPLEADO) 
FROM EMPLEADO e ;

--2
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c 
GROUP BY c.PAIS ;

--3
SELECT ROUND(AVG(p.TOTAL),1) 
FROM PAGO p 
WHERE EXTRACT (YEAR FROM p.FECHA_PAGO)=2009; 

--4
SELECT COUNT(p.CODIGO_PEDIDO) 
FROM PEDIDO p 
GROUP BY p.ESTADO 
ORDER BY COUNT(p.CODIGO_PEDIDO) DESC ;

--5
SELECT MAX(p.PRECIO_VENTA), MIN(p.PRECIO_VENTA)  
FROM PRODUCTO p ;

--6
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c ;

--7
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c , EMPLEADO e ,OFICINA o 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
AND e.CODIGO_OFICINA = o.CODIGO_OFICINA 
AND LOWER(o.CIUDAD)like'madird'; 

--8
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c 
WHERE LOWER(c.CIUDAD) LIKE 'm%' 
GROUP BY c.CIUDAD ;

--9
SELECT e.CODIGO_EMPLEADO , COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c ,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS = e.CODIGO_EMPLEADO 
GROUP BY e.CODIGO_EMPLEADO ;

--10
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c ,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS IS NULL;

--11
SELECT 













