alter session set "_oracle_script"=true;  
create user gestion identified by gestion;
GRANT CONNECT, RESOURCE, DBA TO gestion;

--1
SELECT c.NOMBRE AS NombreCliente ,p.NOMBRE AS NombrePueblo
FROM CLIENTES c , PUEBLOS p 
WHERE c.CODPUE = p.CODPUE ;

--2
SELECT p.NOMBRE AS NombrePueblo, p2.NOMBRE AS NombreProvincia
FROM PUEBLOS p , PROVINCIAS p2 
WHERE p.CODPRO =p2.CODPRO ;

--3
SELECT c.NOMBRE AS cliente, p.NOMBRE AS pueblo, p2.NOMBRE AS provincia
FROM CLIENTES c ,PUEBLOS p ,PROVINCIAS p2 
WHERE c.CODPUE = p.CODPUE 
AND p.CODPRO = p2.CODPRO ;

--4
SELECT DISTINCT p.NOMBRE AS provincia
FROM PROVINCIAS p ,PUEBLOS p2 ,CLIENTES c 
WHERE p.CODPRO = p2.CODPRO
AND p2.CODPUE = c.CODPUE ;

--5
SELECT DISTINCT  a.DESCRIP  
FROM ARTICULOS a ,LINEAS_FAC lf 
WHERE a.CODART = lf.CODART 
AND lf.CANT >10;

--6
SELECT f.FECHA , lf.CODART 
FROM FACTURAS f, LINEAS_FAC lf 
WHERE f.CODFAC = lf.CODFAC 
ORDER BY f.FECHA DESC , lf.CODART , lf.CANT DESC;

--7
SELECT f.CODFAC , f.FECHA 
FROM FACTURAS f , CLIENTES c 
WHERE f.CODCLI =c.CODCLI 
AND c.CODPOSTAL LIKE '%7%';

--8
SELECT f.CODFAC , f.FECHA , c.NOMBRE 
FROM FACTURAS f, CLIENTES c 
WHERE f.CODCLI = c.CODCLI ;

--9
SELECT DISTINCT f.CODFAC , f.FECHA , f.IVA , f.DTO , c.NOMBRE 
FROM FACTURAS f , CLIENTES c 
WHERE f.CODCLI = c.CODCLI 
AND nvl(f.IVA,0)=0
OR f.DTO IS NULL;

--10
SELECT a.PRECIO , a.PRECIO AS PrecioActual,lf.PRECIO  AS precioVendido
FROM LINEAS_FAC lf ,ARTICULOS a 
WHERE lf.CODART = a.CODART 
AND lf.PRECIO  < a.PRECIO ;

--11
SELECT f.CODFAC , f.FECHA , f.IVA , f.DTO ,a.DESCRIP ,lf.PRECIO,lf.DTO  
FROM FACTURAS f , LINEAS_FAC lf , ARTICULOS a 
WHERE f.CODFAC = lf.CODFAC 
AND lf.CODART = a.CODART ;

--12
SELECT f.CODFAC , f.FECHA , f.IVA , f.DTO ,a.DESCRIP ,lf.PRECIO,lf.DTO , c.NOMBRE AS cliente 
FROM FACTURAS f , LINEAS_FAC lf , ARTICULOS a ,CLIENTES c 
WHERE f.CODFAC = lf.CODFAC 
AND lf.CODART = a.CODART 
AND c.CODCLI = f.CODCLI ;

--13
SELECT c.NOMBRE 
FROM CLIENTES c ,PUEBLOS p , PROVINCIAS p2 
WHERE c.CODPUE = p.CODPUE 
AND p.CODPRO = p2.CODPRO 
AND LOWER(p2.NOMBRE)  LIKE '%ma%';

--14
SELECT f.CODCLI 
FROM FACTURAS f , LINEAS_FAC lf , ARTICULOS a 
WHERE f.CODFAC = lf.CODFAC 
AND lf.CODART = a.CODART 
AND a.STOCK < a.STOCK_MIN ;

--15
SELECT DISTINCT a.DESCRIP 
FROM ARTICULOS a ,LINEAS_FAC lf 
WHERE a.CODART = lf.CODART ;

--16
SELECT a.DESCRIP ,nvl(lf.PRECIO,0)- nvl(lf.PRECIO,0) * (nvl(lf.DTO,0) /100) AS precioReal 
FROM LINEAS_FAC lf, ARTICULOS a  
WHERE lf.CODART =a.CODART ;

--17
SELECT DISTINCT a.DESCRIP 
FROM ARTICULOS a , LINEAS_FAC lf ,FACTURAS f ,CLIENTES c, PUEBLOS p ,PROVINCIAS p2 
WHERE a.CODART = lf.CODART 
AND lf.CODFAC = f.CODFAC 
AND f.CODCLI =c.CODCLI 
AND c.CODPUE = p.CODPUE 
AND p.CODPRO = p2.CODPRO
AND LOWER( p2.NOMBRE) LIKE '%a';

--18
SELECT DISTINCT c.NOMBRE 
FROM CLIENTES c , FACTURAS f 
WHERE c.CODCLI = f.CODCLI 
AND f.DTO >10;

--19
SELECT DISTINCT c.NOMBRE 
FROM CLIENTES c , FACTURAS f , LINEAS_FAC lf 
WHERE c.CODCLI = f.CODCLI 
AND f.CODFAC = lf.CODFAC 
AND f.DTO >10
OR lf.DTO >10
OR (f.DTO >10 AND lf.DTO >10);

--20
SELECT a.DESCRIP , lf.CANT, nvl(lf.PRECIO,0)- nvl(lf.PRECIO,0) * (nvl(lf.DTO,0) /100) AS precioReal  
FROM ARTICULOS a , LINEAS_FAC lf , FACTURAS f , CLIENTES c 
WHERE a.CODART = lf.CODART 
AND lf.CODFAC = f.CODFAC 
AND f.CODCLI = c.CODCLI 
AND LOWER(c.NOMBRE) LIKE '%maria mercedes'; 













